### PR TITLE
add_task_bt() now accepts a file-like object

### PR DESCRIPTION
**Pull request by riaqn**
I modify the API of add_task_bt() and it now also accept a file-like object as the torrent file(while keep back-compatibility). I can now write code like this:
```
u = urlopen("http://somesite.com/xxx.torrent")
api.add_task_bt(u)
```
As you can see, it's convenient to add torrent directly from URL, rather than download the torrent first and use that file.

### CODE REVIEW

**Comment by shichao-an** [comment]
Thanks for your PR.

However, I don't quite see the significance of your patch due to the following reasons:

1. **Rare use case**. You are simply uploading torrents by opening a torrent from URL and passing to the API the file-like object on-the-fly. Since this API **mimics a minimal client** (much like a browser), most files to be uploaded are on-disk files. Think of you uploading a file through your web browser; you will choose the file from your filesystem from a window prompted by the browser.
2. **Compatibility issue**. Although you deal a little with this by checking the *file* either to be a string or file-like object, but that is only at the `add_task_bt ` level.  There are still applications that use `upload` and `_req_upload`. 
3. **No feature enhancement**. Using file-like object may gain some performance improvement, but it is bug-prone because the stream's position indicator is handled by users. We want to the postpone the opening of a stream as much as possible to prevent such circumstances as passing an "already-read" file object. Also, having *file* argument treated as either string or file-like object looks anti-pattern and makes the interface more complex.

FYI, you may want to check out [bencode](https://pypi.python.org/pypi/bencode) that converts a torrent into a magnet URI. Then you can pass the magnet URI to `add_task_url`.

**Comment by riaqn** [comment]
Thanks for your reply.
1. I think whether it's "rarely used" depends on specific application, but I agree that for most users the torrent file is on disk(rather in an opened file)
2. Maybe we can check the argument in `upload()` to make it backward-compatible.

**Comment by shichao-an** [comment]
Hi @riaqn ,

Aside from the compatibility, I think it's more of a feature problem as indicated in "3. No feature enhancement" in my previous comment. This happens at `_req_upload` (as far as your code is concerned) instead of `upload` and the critical part is that we cannot get the original filename from the file object (refer to [line 933](https://github.com/shichao-an/115wangpan/pull/26/files#diff-d1f9c413dd6ff506e2bbeeaa4dbe7600R933) in your commit). Also, we can neither predict nor constrain the file-like object passed in while we do care about opening the file with mode `rb` ([distinction](https://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files) depends on whether the platform is Windows or Unix-like, though I never tested my code on Windows) before passing it to the python-requests library. The original intent of this API is to handle as few non-API details as possible.

**Comment by riaqn** [comment]
Hello @shichao-an 
The file name issue can be solved by `file.name`:
```
>>> f = open("tmp/hello", 'rb')
>>> f.name
'tmp/hello'
```
That is, `_req_upload()` can use `file.name` as the uploaded file name.
Meanwhile, I can specify the filename of a torrent from URL like this:
```
u = urlopen('http://somsite.com/xxx.py')
u.name = 'xxx.py'
api.upload(u)
```

As for the open mode problem, there 're two cases:
1. If user pass a string as filename, upload() will open it(with proper mode).
2. If user pass a file object, what we want to make sure is not the mode that user opened it(some file object doesn't even has "mode", like `HTTPResponse`), but that a call to `read()` should return bytes array.

Moving the `isinstance(file, str)` check from `add_task_bt` to `upload` should do the trick.

**Comment by shichao-an** [comment]
Hi @riaqn 

I do believe there must be plenty of ways, as you said, to deal with file objects (however, the problem do exist if you open a binary file with text mode on Windows). But I really don't see this being constructive other than adding extra programmatical complexity. If you are uploading a file from a url, why not passing the the url to `add_task_url`?

**Comment by riaqn** [comment]
Hi @shichao-an 
Yeah I think you 're right. I 'm closing the PR.

**Pull request closed without merging**
